-- Create drippers table
create table if not exists drippers (
  id bigint generated by default as identity primary key,
  name text not null,
  brand text,
  type text, -- e.g. "Flat Bed", "Cone", "Immersion"
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add RLS policies if needed (assuming public read, admin write like grinders)
alter table drippers enable row level security;

create policy "Public drippers are viewable by everyone."
  on drippers for select
  using ( true );

create policy "Users can insert their own drippers."
  on drippers for insert
  with check ( true ); 
  -- Note: In a real app we'd restrict this to admins, but for now matching likely existing loose policies or if auth is handled in app logic.
  -- Based on existing code, server.js handles auth or client uses anon key. 
  -- Admin dashboard uses supabase client directly.

create policy "Users can delete drippers."
  on drippers for delete
  using ( true );
